//SUCCESS
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";

//ERROR
export const ERROR_CREATE_ADDRESS = "ERROR_CREATE_ADDRESS";
export const ERROR_ADDRESS_NOT_FOUND = "ERROR_ADDRESS_NOT_FOUND";
export const ERROR_UPDATE_ADDRESS = "ERROR_UPDATE_ADDRESS";
export const ERROR_DELETE_ADDRESS = "ERROR_DELETE_ADDRESS";
export const ERROR_CHANGE_DEFAULT_ADDRESS = "ERROR_CHANGE_DEFAULT_ADDRESS";
