//SUCCESS
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGOY_SUCCESS = "UPDATE_CATEGOY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "ERROR_CATEGORY_IS_BEING_USED";
export const GET_CATEORIES_SUCCESS = "GET_CATEORIES_SUCCESS";

//ERROR
export const ERROR_CATEGORY_EXISTED = "ERROR_CATEGORY_EXISTED";
export const ERROR_CREATE_CATEGORY = "ERROR_CREATE_CATEGORY";
export const ERROR_CATEGORY_NOT_EXISTED = "ERROR_CATEGORY_NOT_EXISTED";
export const ERROR_THIS_NAME_HAS_ALREADY_BEEN_USED =
  "ERROR_THIS_NAME_HAS_ALREADY_BEEN_USED";
export const ERROR_UPDATE_CATEGORY = "ERROR_UPDATE_CATEGORY";
export const ERROR_CATEGORY_IS_BEING_USED = "ERROR_CATEGORY_IS_BEING_USED";
export const ERROR_DELETE_CATEGORY = "ERROR_DELETE_CATEGORY";
export const ERROR_GET_CATEGORIES = "ERROR_GET_CATEGORIES";
export const ERROR_CATEGORY_NOT_FOUND = "ERROR_CATEGORY_NOT_FOUND";
