//SUCCESS
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

//ERROR
export const ERROR_CREATE_COMMENT = "ERROR_CREATE_COMMENT";
export const ERROR_COMMENT_NOT_FOUND = "ERROR_COMMENT_NOT_FOUND";
export const ERROR_DELETE_COMMENT = "ERROR_DELETE_COMMENT";
