//SUCCESS
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const GET_PRODUCT_PAGINATION_SUCCESS = "GET_PRODUCT_PAGINATION_SUCCESS";
export const GET_PRODUCT_FOR_UPDATE_SUCCESS = "GET_PRODUCT_FOR_UPDATE_SUCCESS";
export const GET_NEWEST_PRODUCT_SUCCESS = "GET_NEWEST_PRODUCT_SUCCESS";
export const GET_MAX_PRICE_SUCCESS = "GET_MAX_PRICE_SUCCESS";
export const FILTER_PRODUCT_SUCCESS = "FILTER_PRODUCT_SUCCESS";
export const COUNT_PRODUCT_SUCCESS = "COUNT_PRODUCT_SUCCESS";

//ERROR
export const ERROR_CREATE_PRODUCT = "ERROR_CREATE_PRODUCT";
export const ERROR_PRODUCT_NOT_FOUND = "ERROR_PRODUCT_NOT_FOUND";
export const ERROR_DELETE_PRODUCT = "ERROR_DELETE_PRODUCT";
export const ERROR_UPDATE_PRODUCT = "ERROR_UPDATE_PRODUCT";
export const ERROR_PRODUCT_ALREADY_EXIST = "ERROR_PRODUCT_ALREADY_EXIST";
export const ERROR_GET_PRODUCT_PAGINATION = "ERROR_GET_PRODUCT_PAGINATION";
export const ERROR_GET_PRODUCT_FOR_UPDATE = "ERROR_GET_PRODUCT_FOR_UPDATE";
export const ERROR_GET_NEWEST_PRODUCT = "ERROR_GET_NEWEST_PRODUCT";
export const ERROR_GET_MAX_PRICE = "ERROR_GET_MAX_PRICE";
export const ERROR_FILTER_PRODUCT = "ERROR_FILTER_PRODUCT";
export const ERROR_COUNT_PRODUCT = "ERROR_COUNT_PRODUCT";
