// SUCCESS
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const GET_MY_ADDRESSES_SUCCESS = "GET_MY_ADDRESSES_SUCCESS";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const UPDATE_USER_SUCESS = "UPDATE_USER_SUCCESS";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS";
export const COUNT_USERS_SUCCESS = "COUNT_USER_SUCCESS";
export const DELETE_ALL_CART_SUCCESS = "DELETE_ALL_CART_SUCCESS";

// ERROR
export const LOGIN_FAIL = "LOGIN_FAIL";
export const ERROR_UPDATE_USER = "ERROR_UPDATE_USER";
export const ERROR_PASSWORD_NOT_MATCH = "ERROR_PASSWORD_NOT_MATCH";
export const ERROR_GET_USER_BY_ID = "ERROR_GET_USER_BY_ID";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
export const ERROR_GET_MY_ADDRESSES = "ERROR_GET_MY_ADDRESSES";
export const ERROR_GET_WISHLIST = "ERROR_GET_WISHLIST";
export const ERROR_ADD_CART = "ERROR_ADD_CART";
export const ERROR_DELETE_CART = "ERROR_DELETE_CART";
export const ERROR_UPDATE_QUANTITY = "ERROR_UPDATE_QUANTITY";
export const COUNT_USERS_ERROR = "COUNT_USERS_ERROR";
export const ERROR_DELETE_ALL_CART = "ERROR_DELETE_ALL_CART";
