//SUCCESS
export const INSERT_WISHLIST_ITEM_SUCCESS = "INSERT_WISHLIST_ITEM_SUCCESS";
export const DELETE_WISHLIST_ITEM_SUCCESS = "DELETE_WISHLIST_ITEM_SUCCESS";

//ERROR
export const ERROR_INSERT_WISHLIST_ITEM = "ERROR_INSERT_WISHLIST_ITEM";
export const ERROR_DELETE_WISHLIST_ITEM = "ERROR_DELETE_WISHLIST_ITEM";
export const ERROR_WISHLIST_ITEM_ALREADY_EXIST =
  "ERROR_WISHLIST_ITEM_ALREADY_EXIST";
export const ERROR_WISHLIST_ITEM_NOT_FOUND = "ERROR_WISHLIST_ITEM_NOT_FOUND";
