export { default as CartIcon } from "./cart";
export { default as DeliveryIcon } from "./delivery";
export { default as FacebookIcon } from "./facebook";
export { default as FutureIcon } from "./future";
export { default as InstagramIcon } from "./instagram";
export { default as LetterIcon } from "./letter";
export { default as LockIcon } from "./lock";
export { default as PhoneIcon } from "./phone";
export { default as ReloadIcon } from "./reload";
export { default as RocketIcon } from "./rocket";
export { default as SearchIcon } from "./search";
export { default as StoreIcon } from "./store";
export { default as TiktokIcon } from "./tiktok";
export { default as TwitterIcon } from "./twitter";
export { default as UserIcon } from "./user";
export { default as WhiteHeartIcon } from "./white-heart";
export { default as UnderlineIcon } from "./underline";
export { default as MobileIcon } from "./mobile";
export { default as RecycleIcon } from "./recycle";
export * from "./heart-fill";
export * from "./chervon-left";
export * from "./chervon-right";
export * from "./trash";
export * from "./heart";
export * from "./circle-minus";
export * from "./circle-plus";
export * from "./edit";
export * from "./delete";
export * from "./bike";
export * from "./loading";
export * from "./pay-online";
export * from "./zalopay";
